name: Go

on:
  push:
    branches: [ master ]
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/**.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test & Coverage
      run: |
        make test

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        verbose: true
